### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JuanVqz** [fastruby/next_rails#114]
## Expected Behavior
Be able to use the Minitest deprecation tracker with Ruby 2.3.8 and Rails 3.2.22.5 using Minitest gem at version 4.7.5

## Actual Behavior

If I run the deprecation tracker it breaks with the following error:

```bash
vendor/bundle/ruby/2.3.0/gems/next_rails-1.3.0/lib/deprecation_tracker.rb:107:in `track_minitest': undefined method `after_run' for MiniTest:Module (NoMethodError)
```

## Possible Fix

I researched for a little bit it seems like the minitest gem at version 

## To Reproduce

1.
2.
3.
4.

## Additional Information

**I will abide by the [code of conduct](https://github.com/fastruby/next_rails/blob/main/CODE_OF_CONDUCT.md)**

**Comment by fbuys** [comment]
Here is some more information that I found for Minitest version 4.7.3.

The below console results show how we can determine that the `after_tests` method exists.
```
irb(main):031:0> Minitest::Unit.respond_to?(:after_tests)
=> true
irb(main):032:0> defined?(Minitest::Unit)
=> "constant"
```

If `after_run` fails but the above results show that `after_tests` is available, then we can use `after_tests` to add the required hook.

**Comment by JuanVqz** [comment]
The workaround we used to solve this:

```ruby
  # config/initializers/minitest.rb

  module Minitest
    def self.after_run(&block)
      Minitest::Unit.after_tests(&block)
    end
  end
```

**Comment by etagwerker** [comment]
@JuanVqz @fbuys Thanks for sharing all this! 

When you have a moment, could you please submit a PR that adds this monkeypatch for applications that are using Minitest < 5.0?

**Comment by fbuys** [comment]
After more investigation it turns out that a simple monkey patch is not enough to get `next_rails` to work with `minitest 4.7`

I believe we need to investigate how to hook into the test suites for `minitest 4.7`.
The Minitest extension we currently use for the deprecation tracker is also not compatible with this version of minitest.

https://github.com/fastruby/next_rails/blob/4752fc9dd4d49d5ca35f779f66622604b208c6f2/lib/deprecation_tracker.rb#L36-L53
